version: '3'

services:
  web:
    build: .
    command: gunicorn my_diary.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=play_that_pen_pong
      - POSTGRES_PASSWORD=twohyeons22!
      - POSTGRES_DB=play_that_pen_pong_dev
volumes:
  postgres_data: