# Generated by Django 4.0.3 on 2022-05-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_alter_guest_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='sticker',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
