# Generated by Django 4.0.3 on 2022-04-07 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('single_pages', '0003_rename_randomq_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='randomQ',
        ),
    ]
