# Generated by Django 4.0.3 on 2022-04-07 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('single_pages', '0004_rename_comment_randomq'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='randomQ',
            new_name='Comment',
        ),
    ]
