# Generated by Django 4.0.3 on 2022-04-07 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('single_pages', '0005_rename_randomq_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
    ]
