# Generated by Django 4.0.3 on 2022-04-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single_pages', '0006_remove_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='question',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
