# Generated by Django 4.0.3 on 2022-06-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single_pages', '0007_comment_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, null=True)),
                ('email', models.EmailField(max_length=30, null=True)),
                ('instagram', models.URLField(null=True)),
                ('mbti', models.CharField(max_length=7, null=True)),
            ],
        ),
    ]
