# Generated by Django 4.0.3 on 2022-06-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single_pages', '0008_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='profile',
            field=models.ImageField(blank=True, upload_to='single_pages/images/%Y/%m/%d/'),
        ),
    ]
