# Generated by Django 4.0.3 on 2022-06-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single_pages', '0009_information_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(blank=True, upload_to='single_pages/images/%Y/%m/%d/')),
            ],
        ),
        migrations.RemoveField(
            model_name='information',
            name='profile',
        ),
    ]
