# Generated by Django 4.0.3 on 2022-07-04 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('single_pages', '0013_alter_avatar_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
