# Generated by Django 4.0.3 on 2022-07-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single_pages', '0014_delete_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
