# Generated by Django 4.0.3 on 2022-07-15 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('single_pages', '0019_alter_todo_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='created_at',
        ),
    ]
