# Generated by Django 4.0.3 on 2022-07-25 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('single_pages', '0020_remove_todo_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
